declare module 'elizabot'
declare module 'https://esm.sh/@langchain/openai'
declare module 'https://esm.sh/@langchain/core/prompts'
declare module 'https://esm.sh/@langchain/core/output_parsers'
declare module 'https://esm.sh/langchain/text_splitter'
declare module 'https://esm.sh/langchain/document'
declare module 'https://esm.sh/langchain/vectorstores/memory'
declare module 'https://esm.sh/@langchain/community/embeddings/ollama'
declare module 'https://esm.sh/langchain/chains/combine_documents'
declare module 'https://esm.sh/langchain/chains/retrieval'
declare module 'https://esm.sh/langchain/document_loaders/web/cheerio'
declare module 'https://esm.sh/cheerio'
declare module 'https://esm.sh/langchain/chains/history_aware_retriever'
declare module 'https://esm.sh/@langchain/core/messages'
declare module "https://esm.sh/langchain/chains"
declare module "https://esm.sh/langchain/memory"
declare module "https://esm.sh/langchain/stores/message/in_memory"
declare module "https://esm.sh/@langchain/core/runnables"
declare module "sqlite3.wasm"